version: '3.8'

services:
  db:
    image: rasulkireev/custom-postgres:15
    restart: always
    environment:
      POSTGRES_DB: ohota_na_skidki_bot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
